name: LobbyMenu
main: me.Stijn.LobbyMenu.Main
version: 0.0.1
author: Stijn van Nieulande
description: LobbyMenu
commands:
   lobbymenu:
      description: LobbyMenu commands
      permission: ngnfw.lobbymenu
      permission-message: You don't have the premission to use the LobbyMenu commands.