##########################################################################
#                   Plugin made by Stijn van Nieulande                   #
##########################################################################
#      ___           ___           ___           ___           ___       #
#     /\__\         /\  \         /\__\         /\  \         /\__\      #
#    /::|  |       /::\  \       /::|  |       /::\  \       /:/ _/_     #
#   /:|:|  |      /:/\:\  \     /:|:|  |      /:/\:\  \     /:/ /\__\    #
#  /:/|:|  |__   /:/  \:\  \   /:/|:|  |__   /::\~\:\  \   /:/ /:/ _/_   #
# /:/ |:| /\__\ /:/__/_\:\__\ /:/ |:| /\__\ /:/\:\ \:\__\ /:/_/:/ /\__\  #
# \/__|:|/:/  / \:\  /\ \/__/ \/__|:|/:/  / \/__\:\ \/__/ \:\/:/ /:/  /  #
#     |:/:/  /   \:\ \:\__\       |:/:/  /       \:\__\    \::/_/:/  /   #
#     |::/  /     \:\/:/  /       |::/  /         \/__/     \:\/:/  /    #
#     /:/  /       \::/  /        /:/  /                     \::/  /     #
#     \/__/         \/__/         \/__/                       \/__/      #
#                                                                        #
##########################################################################
TitleSigns: '[&4Portal&0]'
TitleCommands: '&4Portal &a&l>'